/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import entity.Dich_Vu;
import dao.DichVuDAO;
import db.KetNoiDB;
import dto.DichVuDanhMucDTO;
import entity.Danh_Muc;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author This PC
 */
public class QuanLyDichVu extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyDichVu
     */
    public QuanLyDichVu() {
        initComponents();
        loadTable();
        loadma_danh_muc();
        
    }
  public void loadTable() {
        DichVuDAO dvDAO = new DichVuDAO();
        List<DichVuDanhMucDTO> dvLst = dvDAO.readDichVu();
        DefaultTableModel tblDanhSach = (DefaultTableModel) this.tblDanhSach.getModel();
        tblDanhSach.setRowCount(0);
        for (DichVuDanhMucDTO dv : dvLst) {
            tblDanhSach.addRow(new Object[]{
                dv.getMA_DICH_VU(),
                dv.getTEN_DICH_VU(),
                dv.getGIA(),
                dv.getMIEU_TA(),
                dv.getMA_DANH_MUC(),
                dv.getTEN_DANH_MUC()
            });
        }

    }
    public void loadma_danh_muc() { 
         String sql = "Select MA_DANH_MUC from DANH_MUC";
        try(Connection con = KetNoiDB.getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()){
            cbomadanhMuc.removeAllItems();
            while(rs.next()){
                String ma_danh_muc = rs.getString("MA_DANH_MUC");
                cbomadanhMuc.addItem(ma_danh_muc);
            }
  
        }catch(SQLException e){
        }
     }
    private boolean validateInput() {
    // Kiểm tra nếu tất cả các trường đều trống
    if (txtmaDichVu.getText().trim().isEmpty() && 
        txttenDichVu.getText().trim().isEmpty() && 
        txtdonGia.getText().trim().isEmpty() && 
        txtmieuTa.getText().trim().isEmpty() && 
        cbomadanhMuc.getSelectedIndex() == -1) {
        
        JOptionPane.showMessageDialog(this, "Không được để trống tất cả các trường!");
        return false; // Không hợp lệ
    }
    
    // Kiểm tra các trường khác
    if (txtmaDichVu.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Mã dịch vụ không được để trống!");
        return false;
    }
    if (txttenDichVu.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tên dịch vụ không được để trống!");
        return false;
    }
    if (txtdonGia.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Đơn giá không được để trống!");
        return false;
    }
    if (txtmieuTa.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Mô tả không được để trống!");
        return false;
    }
    if (cbomadanhMuc.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn danh mục!");
        return false;
    }
    
    return true; // Tất cả hợp lệ
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtTimDV = new javax.swing.JTextField();
        txtmaDichVu = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtdonGia = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txttenDichVu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbomadanhMuc = new javax.swing.JComboBox<>();
        txtmieuTa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(720, 630));
        setMinimumSize(new java.awt.Dimension(720, 630));
        setPreferredSize(new java.awt.Dimension(720, 630));

        jTextField1.setBackground(new java.awt.Color(0, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Quản Lý Dịch Vụ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 5));

        txtTimDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimDVActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Mã Dịch Vụ");

        btnThem.setText("Thêm Dịch Vụ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Cập Nhật Thông Tin");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Thông tin dịch vụ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Đơn Giá");

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txttenDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenDichVuActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Tên Dịch Vụ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Mã Danh Mục");

        cbomadanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomadanhMucActionPerformed(evt);
            }
        });

        txtmieuTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmieuTaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Miêu Tả");

        jButton1.setText("DANH MỤC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtmieuTa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTimDV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(txtmaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSua)
                        .addGap(38, 54, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbomadanhMuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttenDichVu)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txttenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbomadanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtmieuTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnLamMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTim)
                    .addComponent(txtTimDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(66, 66, 66))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 5));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Danh sách dịch vụ");

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ", "Đơn Giá", "Miêu Tả", "Mã Danh Mục", "Tên Danh Mục"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txttenDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenDichVuActionPerformed

    private void txtmieuTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmieuTaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmieuTaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       if (!validateInput()) {
        return; // Nếu validation thất bại, không thực hiện hành động tiếp theo
    }
        String maDichVu = txtmaDichVu.getText();
        
        DichVuDAO DvDAO = new DichVuDAO();
        int ketQua = DvDAO.deleteDichVu(maDichVu);
        if(ketQua == 1){
            JOptionPane.showMessageDialog(this, "Thành Công");
            loadTable();
            
        String so0 = tblDanhSach.getValueAt(0, 0).toString();
        String so1 = tblDanhSach.getValueAt(0, 1).toString();
        String so2 = tblDanhSach.getValueAt(0, 2).toString();
        String so3 = tblDanhSach.getValueAt(0, 3).toString();
        String so4 = tblDanhSach.getValueAt(0, 4).toString();
        String so5 = tblDanhSach.getValueAt(0, 5).toString();
        
        txtmaDichVu.setText(so0);
        txttenDichVu.setText(so1);
        txtdonGia.setText(so2);
        txtmieuTa.setText(so3);
        cbomadanhMuc.setSelectedItem(so4);
        }else{
            JOptionPane.showMessageDialog(this, "Thất Bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbomadanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomadanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbomadanhMucActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        int soDongChon = tblDanhSach.getSelectedRow();
        String so0 = tblDanhSach.getValueAt(soDongChon, 0).toString();
        String so1 = tblDanhSach.getValueAt(soDongChon, 1).toString();
        String so2 = tblDanhSach.getValueAt(soDongChon, 2).toString();
        String so3 = tblDanhSach.getValueAt(soDongChon, 3).toString();
        String so4 = tblDanhSach.getValueAt(soDongChon, 4).toString();
        String so5 = tblDanhSach.getValueAt(soDongChon, 5).toString();
        
        txtmaDichVu.setText(so0);
        txttenDichVu.setText(so1);
        txtdonGia.setText(so2);
        txtmieuTa.setText(so3);
        cbomadanhMuc.setSelectedItem(so4);
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (!validateInput()) {
        return; // Nếu validation thất bại, không thực hiện hành động tiếp theo
    }
        
        int ma_dich_vu = Integer.parseInt(txtmaDichVu.getText());
        String ten_dich_vu = txttenDichVu.getText();
        double gia = Double.parseDouble(txtdonGia.getText());
        String mieu_ta = txtmieuTa.getText();
        int ma_danh_muc =  Integer.parseInt(cbomadanhMuc.getSelectedItem().toString());
       

        Dich_Vu dv = new Dich_Vu(ma_dich_vu, ten_dich_vu, gia, mieu_ta, ma_danh_muc);

        DichVuDAO DvDAO = new DichVuDAO();
        int ketQua = DvDAO.createDichVU(dv);
     
        if (ketQua == 1) {
            JOptionPane.showMessageDialog(this, "Thành Công");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thất Bại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtmaDichVu.setText("");
   txttenDichVu.setText("");
   txtdonGia.setText("");
    txtmieuTa.setText("");
    if (cbomadanhMuc.getItemCount() > 0) {
        cbomadanhMuc.setSelectedIndex(0);
    }
    txtmaDichVu.requestFocus();
    loadTable();
    loadma_danh_muc();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtTimDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimDVActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (!validateInput()) {
        return; // Nếu validation thất bại, không thực hiện hành động tiếp theo
    }
        int ma_dich_vu = Integer.parseInt(txtmaDichVu.getText());
        String ten_dich_vu = txttenDichVu.getText();
        double gia = Double.parseDouble(txtdonGia.getText());
        String mieu_ta = txtmieuTa.getText();
        int ma_danh_muc =  Integer.parseInt(cbomadanhMuc.getSelectedItem().toString());
        
        
        Dich_Vu dv = new Dich_Vu(ma_dich_vu, ten_dich_vu, gia, mieu_ta, ma_danh_muc);
        DichVuDAO dao = new DichVuDAO();
       
       int ketQua = dao.updateDichVu(dv);
      if (ketQua == 1) {
            JOptionPane.showMessageDialog(this, "Thành Công");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thất Bại");
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
       DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
       DichVuDAO dvDAO = new DichVuDAO();
        try {
            int madichvu = Integer.parseInt(txtTimDV.getText()); // Lấy mã tài khoản từ JTextField
            DichVuDanhMucDTO dvDTO = dvDAO.timDichVu(madichvu); // Gọi phương thức tìm kiếm
          
            model.setRowCount(0); // Xóa tất cả các hàng trong bảng

            if (dvDTO != null) {
                // Thêm tài khoản tìm thấy vào bảng
                model.addRow(new Object[]{
                dvDTO.getMA_DICH_VU(),
                dvDTO.getTEN_DICH_VU(),
                dvDTO.getGIA(),
                dvDTO.getMIEU_TA(),
                dvDTO.getMA_DANH_MUC(),
                dvDTO.getTEN_DANH_MUC() // <-- sửa dòng này
});

            } else {
                // Hiển thị thông báo không tìm thấy tài khoản
                
                JOptionPane.showMessageDialog(this, "Không tìm thấy dịch vụ với mã: " + madichvu);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã dịch vụ hợp lệ.");
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Quanlydanhmuc qldm = new Quanlydanhmuc();
        qldm.setVisible(true);
        qldm.setDefaultCloseOperation(Quanlydanhmuc.DISPOSE_ON_CLOSE);
  
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbomadanhMuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtTimDV;
    private javax.swing.JTextField txtdonGia;
    private javax.swing.JTextField txtmaDichVu;
    private javax.swing.JTextField txtmieuTa;
    private javax.swing.JTextField txttenDichVu;
    // End of variables declaration//GEN-END:variables
}
