/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DanhMucDAO;
import dao.DichVuDAO;
import entity.Danh_Muc;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Hong Kien
 */
public class Quanlydanhmuc extends javax.swing.JFrame {

    /**
     * Creates new form Quanlydanhmuc
     */
    public Quanlydanhmuc() {
        initComponents();
        loadTable();
    }
      public void loadTable() {
        DanhMucDAO dmDAO = new DanhMucDAO();
        List<Danh_Muc> dmLst = dmDAO.readDanhMuc();
        DefaultTableModel tblDanhSach = (DefaultTableModel) this.tblDanhSach.getModel();
        tblDanhSach.setRowCount(0);
        for (Danh_Muc dm : dmLst) {
            tblDanhSach.addRow(new Object[]{
                dm.getMA_DANH_MUC(),
                dm.getTEN_DANH_MUC()
            });
        }

    }
      private boolean validateInput() {
    if (txtmaDanhMuc.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Mã danh mục không được để trống!");
        txtmaDanhMuc.requestFocus();
        return false;
    }
    if (txttenDanhMuc.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tên danh mục không được để trống!");
        txttenDanhMuc.requestFocus();
        return false;
    }
    return true;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmaDanhMuc = new javax.swing.JTextField();
        txttenDanhMuc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtTimDm = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Danh Mục");

        jLabel2.setText("Tên Danh Mục");

        txtmaDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaDanhMucActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Danh Mục", "Tên Danh Mục"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel3.setText("Quản Lý Danh Mục");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel3)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Làm mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Tìm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtTimDm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimDmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttenDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtmaDanhMuc)
                    .addComponent(txtTimDm))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(txtTimDm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaDanhMucActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!validateInput()) {
        return;
    }
        int ma_danh_muc = Integer.parseInt(txtmaDanhMuc.getText());
        String ten_danh_muc = txttenDanhMuc.getText();
      
       

        Danh_Muc dm = new Danh_Muc(ma_danh_muc, ten_danh_muc);

        DanhMucDAO DmDAO = new DanhMucDAO();
        int ketQua = DmDAO.createDanhMuc(dm);
     
        if (ketQua == 1) {
            JOptionPane.showMessageDialog(this, "Thành Công");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thất Bại");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (!validateInput()) {
        return;
    }  
        int ma_danh_muc = Integer.parseInt(txtmaDanhMuc.getText());
       String ten_danh_muc = txttenDanhMuc.getText();
        
        
      Danh_Muc dm = new Danh_Muc(ma_danh_muc, ten_danh_muc);
        DanhMucDAO dao = new DanhMucDAO();

       int ketQua = dao.updateDanhMuc(dm);
      if (ketQua == 1) {
            JOptionPane.showMessageDialog(this, "Thành Công");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thất Bại");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!validateInput()) {
        return;
    }
        String madanhMuc = txtmaDanhMuc.getText();
        DanhMucDAO DmDAO = new DanhMucDAO() ;
        int ketQua = DmDAO.deleteDanhMuc(madanhMuc);
        if(ketQua == 1){
            JOptionPane.showMessageDialog(this, "Thành Công");
            loadTable();
            
        String so0 = tblDanhSach.getValueAt(0, 0).toString();
        String so1 = tblDanhSach.getValueAt(0, 1).toString();
        
        
        txtmaDanhMuc.setText(so0);
        txttenDanhMuc.setText(so1);
    
        }else{
            JOptionPane.showMessageDialog(this, "Thất Bại");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    txtmaDanhMuc.setText("");
    txttenDanhMuc.setText("");
 
    loadTable();
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        int soDongChon = tblDanhSach.getSelectedRow();
        String so0 = tblDanhSach.getValueAt(soDongChon, 0).toString();
        String so1 = tblDanhSach.getValueAt(soDongChon, 1).toString();
       
        txtmaDanhMuc.setText(so0);
        txttenDanhMuc.setText(so1);
        
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
        DanhMucDAO dmDAO = new DanhMucDAO();
        try {
            int madanhmuc = Integer.parseInt(txtTimDm.getText()); // Lấy mã tài khoản từ JTextField
           Danh_Muc dm = dmDAO.timDanhMuc(Integer.parseInt(txtTimDm.getText())); // Gọi phương thức tìm kiếm
          
            model.setRowCount(0); // Xóa tất cả các hàng trong bảng

            if (dm != null) {
                // Thêm tài khoản tìm thấy vào bảng
                model.addRow(new Object[]{
                dm.getMA_DANH_MUC(),
                dm.getTEN_DANH_MUC() // <-- sửa dòng này
});

            } else {
                // Hiển thị thông báo không tìm thấy tài khoản
                
                JOptionPane.showMessageDialog(this, "Không tìm thấy danh mục với mã: " + madanhmuc);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã danh mục hợp lệ.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtTimDmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimDmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimDmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlydanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlydanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlydanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlydanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quanlydanhmuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtTimDm;
    private javax.swing.JTextField txtmaDanhMuc;
    private javax.swing.JTextField txttenDanhMuc;
    // End of variables declaration//GEN-END:variables
}
