/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import db.KetNoiDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author This PC
 */
public class TraPhongJFrame extends javax.swing.JFrame {
    public int MaTaiKhoan;
    public int MaKhachHang;

    /**
     * Creates new form TraPhongJFrame
     */
    public TraPhongJFrame() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        fillCbo1();
    }
    
    public void fillCbo1() { 
        String sql = "Select MA_HOA_DON from HOA_DON WHERE TRANG_THAI_THANH_TOAN = 0";
        try(Connection con = KetNoiDB.getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
     

            while(rs.next())
                String ma_hoa_don = rs.getString("MA_HOA_DON");
                 cboMaHoaDon.addItem(ma_hoa_don);
                }
                ch(SQLException e){ 
        }
     }  
    public void setText(int ma){
        String sql = "Select MA_TAI_KHOAN from HOA_DON WHERE MA_HOA_DON = ? ";
        try(Connection con = KetNoiDB.getConnection();
             Pr eparedStatement  ps = con.prepareStatement(sql);){
         
     

            ResultSet rs = ps.e xecuteQuery();
            while(rs.next()){
                 int ma_tai_khoan = rs.getInt("MA_TAI_K
                    txtMaTaiKhoan.setText(String.valueOf(ma_tai_kh o

            ch(SQLExceptione){
        }
    }  
    public void setText2(int ma){
        String sql = "Select MA_KHACH_HANG from HOA_DON WHERE MA_HOA_DON = ? ";
        try(Connection con = KetNoiDB.getConnection();
             Pr eparedStatement  ps = con.prepareStatement(sql);){
            
     

            ResultSet rs = ps.ex ecuteQuery();
            while(rs.next()){
                 int ma_khach_hang = rs.getInt("MA_KHAC
                    txtMaKhachHang.setText(String.valueOf(ma_khach _

            ch(SQLExceptione){
        }
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WA RNING : Do NOT modify  this code. The content of this method is always
     * regenerated by the Form Editor.
     

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachHoaDon = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
    // 
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        btnQuayLai = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        cboMaHoaDon = new javax.swing.JComboBox<>();
        txtMaKhachHang = new javax.swing.JTextField();
        txtMaTaiKhoan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDanhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
                new String[] {
                        " Tên", "Giờ Vào", "Giờ Ra", "Giá ph òn
                          
                          
                        a ne1.setViewportView(tblDanhSachHoa D
                
                el2.setBorer(j
                        
                ejLabel8.setText("Tiền Nhận");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Tiền Thừa");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Tổng Cộng");

        jButton1.setText("Xuất Hóa Đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thanh Toán");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        jTextField5.setEditable(false);

        btnQuayLai.setText("QUAY LẠI");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLa
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELA
                                    .addComponent(jTextField1, javax.sw
                                    .addGroup(jPane
                                        .addComponent(j
                                        Label9)
                                            .addPreferredGap(javax.swing.LayoutStyle.Co
                                                .addComponent(jTextFie
                                                18, 18, 18)
                                                p(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.L
                                                        ADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton2
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1))
                                    .addGroup(jPane
                                        .addComponent(j
                                        Label11)
                                            .addPreferredGap(javax.swing.LayoutStyle.Co
                                                .addComponent(jTextFiel
                                                erredGap(javax.swin
                                                onent(btnQuayLai)
                                        Gap(23, 23, 23))
                                                
                                                tVerticalGroup(
                                                t.createParallelGroup(javax.
                                Group(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.crea
                                        eSequentialGroup()
                                .addContainerGap(20, Shor
                                .addGroup(jPanel2Lay            .addComponent(jLabel8)
                    .addComponent(jText
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, 
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.Grou
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layou
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE
                                                 39, javax.swing.GroupLayout.PREFERRE
                                                _SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                39, javax.swing.GroupLayout.PREFERRED_S
                                            .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SI
                                                E, 39, javax.swing.GroupLayout.PREFER
                                                ED_SIZE))
                                    .addGroup(jPane
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing
                                            .addComponent(jLabe
                                                l9)))
                                                13, 13, 13))
                                                        
                                                
                                                        
                                                
                                                        
                                        ackground(new java.awt.
                                                Color(0, 255, 255));
                                                
                                                        
                                                        
                                                new java.awt.Font("Arial
                                setText("HÓA ĐƠN TÍN
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
                el1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                Group(javax.swing.GroupLayout.Alignmen
                                .addContainerGap(28, Short.MAX_VALUE)
                                        
                                .addComponent(jLabel3)        .addGap(15, 15, 15))
        );
                
                        el1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                                setText("Tên Quán");
                                
                                setFont(new java.awtjLabel2.setText("Địa Chỉ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Mã Hóa Đơn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Khách Hàng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Tài Khoản");

        jTextField3.setEditable(false);
        jTextField3.setText("KARAOKE THÁI TỬ");

        jTextField4.setEditable(false);
        jTextField4.setText("1051 Tôn Đức Thắng, Sở Dầu, Hồng Bàng, Hải Phòng");

        cboMaHoaDon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaHoaDonActionPerformed(evt);
            }
        });

                
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layo
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLay
                                        .addGroup(layout.createSequentialGroup()
                                
                                            .addComponent(jLabel
                                                .ad
                                                .addComponent(txtMaKhachHang))
                                                .addGroup(layout.createSequentia
                                                        .addComp
                                                        onent(jLabel4)
                                                                
                                                            .addPreferredGap(javax.swing.LayoutS
                                                                .addComponent(cboMaHoa
                                                                38, 38, 38)
                                                                        
                                                                onent(jLabel6)
                                                        Gap(18, 18, 18)
                                                                onent(txtMaTaiKhoan, j
                                                                yout.createSequen
                                                                        tialGroup()
                                                                p(layout.createParallelGro
                                                                        p(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        
                                                    .addComponent(j
                                                    .addComponent(jLab
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignme
                                                        t.LEADING)
                                                .addComponent(jTextField4, javax
                                                    .addComponen
                                                        t(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, jav
                                                        rGap(52, Short.MAX_VAL
                                                        .createSequentialGroup(
                                                p(layout.createPara
                                                Component(jScrol
                                                        lPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        onent(jPanel2, javax.swing
                                                                GroupLayout.DEFAULT_SIZE, javax.swing.GroupL
                                                                yout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        rGap())
                                                                
                                                                
                                
                        ut.setVerticalGroup(
                                ut.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        p(layout.createSequentialGroup()
                                        Component(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, j
                                                vax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLa
                                .addGap(30, 30, 30)        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponen
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_
                            .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.A
                                        ignment.BASELINE)
                                    .addComponent(j
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swi
                                        Gap(28, 28, 28)
                                        Group(layout.createParallelGroup(javax.swing.GroupLayout.Alignment
                                                BASELINE)
                                                
                                    .addComponent(j
                                    .addComponent(jLabel6)
                                        .addComponent(cboMaHoa
                                        .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZ
                                                , javax.swing.GroupLayout.DEFAULT_SIZ
                                                , javax.swing.GroupLayout.PREFERRED_SIZE
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtMaKha
                                        Gap(18, 18, 18)
                                                
                                                
                                        Component(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259,
                                                javax.swing.GroupLayout.PREFERRED_SIZ
                                                )
                                .addPreferredGap(ja
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.Group
                                        ContainerGap(javax.swi
                                        
                                                
                                                
                                
                                
                                        
                                -fold>//GEN-END:initComponents
                                
                                        
                                 jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:ev// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed 

    pri vate void cboMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaHoaDonActionPerformed
        cboMaHoaDon.addActionListener(new ActionListener() {
        @Override 
        public void actionPerformed(ActionEvent e) {
             setText(Integer.parseInt((String) cboMaHoaDon.getSelectedItem()));
            setText2(Integer.parseInt((String) cboMaHoaDon.getSelectedItem()));
        } 
});
            EN-LAST:e
            
                void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//
                ose(); // Đóng form hiện tại
            X
            }//GEN-LAST:event_btnQuayLaiActionPerformed
 
    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
        // 
          
         *          javax.swing.UIManager.setLookAndFeel(info.getClassName());
         * 
                    break;
         * 
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        //</editor-fold>
                    

        /* Create and display the form */
                    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    
                new TraPhongJFrame().setVisible(true);
             }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JComboBox<String> cboMaHoaDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblDanhSachHoaDon;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtMaTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
    }
}
